### ISSUE TITLE
setup solr

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/data-catalogue#1]
# To do
1. start from [`docker-compose.yml`](https://github.com/ebi-ait/data-catalogue/blob/main/docker-compose.yml) file in repo
2. follow the [collection and schema creation steps](https://solr.apache.org/guide/solr/latest/getting-started/tutorial-five-minutes.html#create-a-collection) from this tutorial

<summary>example schema.xml
<details>

```xml

<!-- example schema.xml -->

<schema name="example_schema" version="1.6">
  <!-- Fields for Datasets -->
  <field name="id" type="string" indexed="true" stored="true" required="true" multiValued="false" />
  <field name="dataset_name" type="text_general" indexed="true" stored="true" />
  <field name="description" type="text_general" indexed="true" stored="true" />

  <!-- Fields for Fields within Datasets -->
  <field name="field_id" type="string" indexed="true" stored="true" required="true" multiValued="false" />
  <field name="field_name" type="text_general" indexed="true" stored="true" />
  <field name="field_type" type="text_general" indexed="true" stored="true" />

  <!-- Fields for Institutes -->
  <field name="institute_id" type="string" indexed="true" stored="true" required="true" multiValued="false" />
  <field name="institute_name" type="text_general" indexed="true" stored="true" />

  <!-- Dynamic Fields for Additional Metadata -->
  <dynamicField name="*_s" type="string" indexed="true" stored="true" />

  <!-- Unique Key -->
  <uniqueKey>id</uniqueKey>

  <!-- Copy Fields for Easy Querying -->
  <copyField source="dataset_name" dest="text"/>
  <copyField source="field_name" dest="text"/>
  <copyField source="institute_name" dest="text"/>
</schema>

```

</details>
</summary>

3. add a few dataset documents using the rest api

<summary>example dataset document
<details>

```xml
<!-- Dataset document -->
<doc>
  <field name="id">123</field>
  <field name="dataset_name">Sample Dataset</field>
  <field name="institute_name">ABC Institute</field>
  <!-- Other dataset fields -->
</doc>

```
</summary>

The institute fields can be added with the dataset or separately:
<summary>example institute document
<details>

```xml

<!-- Institute document -->
<doc>
  <field name="id">1</field>
  <field name="institute_name">ABC Institute</field>
  <!-- Other institute fields -->
</doc>

```

</details>
</summary>
 

4. perform some search queries

Aggregation by institute.
```bash
curl http://localhost:8983/solr/your_collection/select?q=*:*&facet=true&facet.field=institute_name
 ```

Search by institute name
```bash
http://localhost:8983/solr/your_collection/select?q=institute_name:"Your Institute Name"
```

# done means:
- [ ] a running solr server
- [ ] a script with the api commands used to create the collection and schema
- [ ] a script that loads a few documents
- [ ] a script with a few query examples

**Comment by snathanvj** [comment]
Content of book_solr.json
`[
    {
        "id": "978-0641723221",
        "cat": [
            "book",
            "hardcover"
        ],
        "name": "The Book Thief",
        "author": "Markus Zusak",
        "series_t": "WW2",
        "sequence_i": 1,
        "genre_s": "history war",
        "inStock": false,
        "price": 6.99,
        "pages_i": 200
    },
    {
        "id": "978-1423103349",
        "cat": [
            "book",
            "paperback"
        ],
        "name": "All the Light We Cannot See",
        "author": "Anthony Doerr",
        "series_t": "WW2",
        "sequence_i": 2,
        "genre_s": "history war fiction",
        "inStock": true,
        "price": 8.49,
        "pages_i": 500
    }
]`
