### ISSUE TITLE
Arrange Checklist editor meeting

### ISSUE THREAD

**Issue by Jeena-Rajan** [ebi-ait/data-catalogue#105]
Arrange meeting for Amnon, Rasko and Isuru to discuss tasks and steps required for checklist editor development

**Comment by amnonkhen** [comment]
Meeting took place 17/4 @ 9:15.
We captured the proposed architecture in a [miro board](https://miro.com/app/board/uXjVKUO2kFw=/).
It also contains diagrams describing the current architecture and the steps in the migration process.
