### ISSUE TITLE
Outline tasks and phases for checklist editor

### ISSUE THREAD

**Issue by Jeena-Rajan** [ebi-ait/data-catalogue#106]
Create a document to outline the stages, phases and tasks for checklist editor development  

See: https://miro.com/app/board/uXjVKUO2kFw=/

**Comment by theisuru** [comment]
[doc](https://docs.google.com/document/d/1F3o3vhMUB3UJ4-wOEg5rsEwpt7RMWfI8vito4xKGWAg/edit)
