### ISSUE TITLE
connect github repo to devsandbox

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/data-catalogue#11]
- [ ] account in code sandbox for each team member
- [ ] connect https://github.com/ebi-ait/data-catalogue to dev sandbox
- [ ] branch per feature so each has their own demo

**Comment by theisuru** [comment]
- Created a team in [codesandbox (ebi-ait)](https://codesandbox.io/p/github/ebi-ait/data-catalogue/main?file=%2Fangular.json%3A105%2C1&workspaceId=ee67443e-1886-4e7b-82c7-fdb706050e72) and sent invitations to team members (Amnon, Senthil)
- Connected main branch of data-catalogue with codesandbox. 
- Sent a request to connect codesandbox with Github (github app). Request is sent to organisation admin, needs to accept it (Hopefully Amnon can see it)

In therory this should add an auto commit with a demo link, need to see how this work once the app request is accepted.
