### ISSUE TITLE
add a "Status" column and re-add ‘Expected Release’ column 

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/data-catalogue#22]
'Status' column should replace  'Available Datasets' [here](https://9pw39w-4200.csb.app/) - DONE

15/01/24
***** Below no longer required at this time********
Add ‘Expected Release’ column between ‘Centre’ and “Available Datasets’ (reads from ‘Expected Release column on spreadsheet)

use the ‘Expected Release’ column to distinguish released and non released studies.

**released** - show a download/explore link
         - Currently only row 11 (JAX_RNAseq_ExtraEmbryonic) has data for Release 1
         - Status column should link to S3 bucket URL (speak to Dipayan about this)
         
**unreleased** - show the release dates

Example form the cellbygene site:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU9XQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf7fcab3339a5702b20e94c9f111eb673a663df9/image.png" alt="image.png" />

**Comment by Jeena-Rajan** [comment]
From Gabby:
Jeena I am OK to call that column 'Status'. Under it I as the primary user from below, I would expect either Download/Explore, or if not, text Expected 2024
Basically, there are two users, for which the needs are different.
User of the data portal/consumer:

is this dataset available for me to Explore/Download or not?
if yes - ‘Explore/Download’ button (depends what we are giving them whe somethig is released)

if no - text ‘Available 2024’

User of the spreadsheet - more internal stakeholder/collaborator
how are the DPCs getting on with data availability, ad what is their status?
Expected 2024
Uploaded etc

As we at the moment are looking at the first user for the data catalogue, I feel we should just address the first user's needs in the design. Will copy this in the requiremets for the designner as well

**Comment by Jeena-Rajan** [comment]
‘Expected Release’ column no longer required as communicated by MorPhiC team so closing ticket.
