### ISSUE TITLE
quick & dirty eLwazi catalogue

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/data-catalogue#25]
Do it base on a branch of the data-catalogue repo where the data file and configuration file are changed.
This is to have something tangible whilst we turn the catalogue's grid into a sharable Angular module.

**Comment by theisuru** [comment]
Demo after chaning data data.json and few fields. Suggesstions are wellcome. 
https://gxcdyq-4200.csb.app/

Suggesstions:
- better representation of boolean fields
- wrap header names
- when you hover on truncated cells, there should be a popup with the full (or less truncated) text
- I think eLwazi has its own colour palette. It would be a good exercise to use it.

**Comment by theisuru** [comment]
Closing this task and moving UI tasks to another ticket because they are taking lot of time.
