### ISSUE TITLE
Implement filters/facets for complex data types

### ISSUE THREAD

**Issue by theisuru** [ebi-ait/data-catalogue#27]
If data type is array or a map (accessing nested fields), current filtering will not work. For each of these complex data types filters needs to be implemented. 
- Array
- Nested fields

**Comment by amnonkhen** [comment]
There is a bug in the behaviour:
The filtering should be "AND" between fields and "OR" within the field.

**Comment by theisuru** [comment]
This has been done in eLwazi branch. We will keep this in eLwazi branch until we are done with the Morphic F2F meeting end of January 2024. Once this meeting is over, we will merge these changes to the main branch, thinking about the merging and what needs to be in the `main` branch.

**Comment by theisuru** [comment]
Another issue is created for merging task. So this can be closed.
