### ISSUE TITLE
Make Demo data view default and remove the one row only view

### ISSUE THREAD

**Issue by Jeena-Rajan** [ebi-ait/data-catalogue#28]
Only show one view in MorPhiC tracker/catalogue which is the demo data view. 
- [ ] Remove 'Show Demo Data' tickbox
- [ ] Change 'Data Catalogue' to 'Study Tracker' on top left

**Comment by snathanvj** [comment]
Should I make changes in demo branch or main branch. If it is main branch it does not compile.

Error: src/app/services/grid-utils.service.ts:6:43 - error TS2307: Cannot find module '../extensions/status-cell-renderer/status-cell-renderer.component' or its corresponding type declarations.

6 import {StatusCellRendererComponent} from "../extensions/status-cell-renderer/status-cell-renderer.component";

if any of you forgot to commit any local changes , could you please push the changes.

**Comment by snathanvj** [comment]
Pushed changes to master.
