### ISSUE TITLE
eLwazi Catalogue spinup

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/data-catalogue#30]
Status:
- first version done by @theisuru 
- available on http://elwazicatalogue.ilifu.ac.za/
- [code](https://github.com/elwazi/projects-index) in [elwazi](https://github.com/elwazi) github. It is a fork of hca project catalogue.

Next steps:
- second version available on: https://gxcdyq-4200.csb.app/
- collect required capabilities from community
- decide technology: do we continue with hca catalogue code and make it extensible? Do we move to a platform like Google Data Studio ([see example](https://lookerstudio.google.com/reporting/01025982-ad3e-4331-98d4-e63d8c9f9730/page/QZOmC))?

**Comment by Wkt8** [comment]
Awaiting a concept document which will specify requirements being created by Lyndon - to be shared here
