### ISSUE TITLE
Importing data to the catalogue

### ISSUE THREAD

**Issue by Jeena-Rajan** [ebi-ait/data-catalogue#32]
There are multiple user stories here: 

- As a catalogue manager, I want a spreadsheet-based submission interface (e.g. upload a spreadsheet containing metadata) that can add datasets to the catalogue, so that the catalogue can be updated (cadence not important right now)  

**Acceptance Criteria / Definition of Done**

* Given a spreadsheet containing metadata
* When the spreadsheet containing metadata is completed 
* The catalogue can be updated to include the dataset and metadata in the spreadsheet

**Comment by Wkt8** [comment]
Obtain metadata and spreadsheet via email at the moment
