### ISSUE TITLE
faceted search sidebar look and feel

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/data-catalogue#36]

**Comment by theisuru** [comment]
- New designer UI has a search box, not sure it can be done using existing angular component. Need to discuss what we can use here.

**Comment by amnonkhen** [comment]
This can be done using [Chips Autocomplete
](https://material.angular.io/components/chips/examples#chips-autocomplete).

**Comment by theisuru** [comment]
Review functionality and then move onto styling.
