### ISSUE TITLE
eLwazi Customisation of Data Catalogue 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/data-catalogue#56]
Available on: https://gxcdyq-4200.csb.app/

Title
- [x] Change title to 'eLwazi Data Catalogue' 

Search Dataset Text
- [x] Change 'search by genes, cell lines, etc..' to 'search by project, regions, etc.' 

Column Names
- [x] Change 'Cohort Name' to 'Project Name'
- [x] Change 'Countries' to 'Regions'

Filters Text
- [x] Change 'Cohort Name' to 'Project Name'
- [x] Change 'Countries' to 'Regions'

Style / Branding
- [ ] Add eLwazi colors and logos (Branding information here: https://drive.google.com/drive/folders/1QYt6Dfwprqz9Jym7Ye-DQYdellSJeT4G)
- [ ] Example: http://154.114.10.189/

**Comment by theisuru** [comment]
Adding eLwazi colors and Logos to be done later once we decided to merge with `main` branch
