### ISSUE TITLE
ux requirements

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/data-catalogue#6]
see [miro board with wireframes](https://miro.com/app/board/uXjVNP8Hn2Q=/)
This is a list of UX requirements from the catalogue.
Each one would be prioritised and added to the backlog
- [x] free text search
- [x] column selection
- [x] color palette
- [x] hyperlink from some columns, e.g. JAX->JAX website
- [ ] canned column ordering - by gene, by dpc
- [x] nice header
- [ ] remove GEO links (see below), Status and Expected release [see request below](https://app.zenhub.com/workspaces/fairification-63c67b0688ee4e002b2890b3/issues/gh/ebi-ait/data-catalogue/6#issuecomment-1864297432)
- [ ] popup text on hover for truncated long cell values
- [ ] target gene side filter

**08/01/23**
For the single source of truth for the Data Catalogue there is a [spreadsheet copy](https://docs.google.com/spreadsheets/d/1OpU8S_r0GiBHsxlJy0K6n0B9G3VJgWVJ1EC2QOQ_xzM/edit#gid=0) of the [parent spreadsheet] (https://docs.google.com/spreadsheets/d/1rrnZigsSrMFKggM3KytHlRc80GtAV6kvZUqPGvrUw5w/edit#gid=0) which is dataset specific (does not include study tracking information). This dataset specific spreadsheet contains a subset of the columns required to show datasets for the catalogue. The parent spreadheet will feed this data catalogue source spreadsheet and two new columns have been added to the parent spreadsheet to help with this:
1) Column AB (Release No.) - indicates which release the dataset is part of 
2) Column AC (To be included in next release) column indicating the data should be included in the next release.

**Comment by gabsie** [comment]
Hi, @amnonkhen and @Jeena-Rajan 

We got together on Friday to discuss feedback on the suggested catalogue. Here are the most important points, and this can all evolve and be improved in the future. 

1. Order of columns to be as Miro board: https://miro.com/app/board/uXjVNeLjeBc=/ 
2. Newest additions of studies should appear at the top (this might be more relevant for the future when we keep track of entry)
3. Study titles need fixing - they should be as per the Studies from the list of studies (Study title column D)
4. Titles - Underscores should be removed and be sensible
5. The Search at the top should be primarily a Gene search, and should say that
6. Additionally, I guess in a similar way to how https://explore.data.humancellatlas.org/projects works on the side, we should have the options, as per the Miro: 
 - Cell type
 - Assay
 - Perturbation type
 - Model system
7. There is some sort of bug with Expected release  - it doesn't gather that from the file 
8. The options per column - I think at the moment this is too many options provided. Maybe it should just function as the quick filter. 

This is not for the MVP, we should still think how to deal with the Cell lines for the future. 

Cell lines - should be links to repositories which store them (not for the MVP)

Please ask us questions if anything is not clear.

@ESapenaVentura and @anu-shiva - you guys add anything else if you want.

Thanks. 
Gabby

**Comment by Jeena-Rajan** [comment]
Hi @gabsie, have requested some clarifications under your points in bold above.
Also, can you give some timeline for when styling can be provided as preumably this is needed for the MVP?

**Comment by gabsie** [comment]
Hey, just pasting some more feedback here ahead of the demo tomorrow:

- we can get rid of the Status and Expected release columns for now
- if the side dropdowns become smaller, maybe the column names will be readable. This is something we should make sure is possible.
- Target genes should also be visible

**Comment by Jeena-Rajan** [comment]
Thanks @gabsie , can you clarify the third point (target genes should be visible)? What would you like to see here, could you put an example in the ticket please? Isuru and Senthil have will ensure points 1 and 2 will be done for tomorrow's demo. Also, would you like Isuru to demo this or do you plan to do this?

**Comment by gabsie** [comment]
I meant that the title of the column, but also the genes below should be visible, at the moment only the beginning of them is shown?

**Comment by Jeena-Rajan** [comment]
The removal of the 'Status' and 'Expected release' columns enables the 'Target Genes' column to be visible. How would you like the genes viewed as they're currently comma separated? I understand there may be hundreds of genes associated with a study so maybe this could be a discussion point tomorrow at the DRACC.

**Comment by Jeena-Rajan** [comment]
Based on the feedback from the [proj-morphic](https://embl-ebi-ait.slack.com/archives/C04MB89JVUK/p1702989311109899?thread_ts=1702904919.062019&cid=C04MB89JVUK) slack we need to change the following:

1) Read ‘Expected Release’ column between ‘Centre’ and “Available Datasets’ (reads from ‘Expected Release column on spreadsheet)
2) Remove GEO links
3) Change column title from  ‘Available Datasets’ to ‘Data Availability’ 
4) Data availability should link to S3 bucket URL (speak to Dipayan about this)

GEO link removal was requested as this data is old and currently doesn't add anything, we will need this in future.
Also need to think abuot how to display genes so they are more visible. 

There is a copy of the spreadsheet that informs the data catalogue on a local EBI Google folder which can be modified: https://docs.google.com/spreadsheets/d/1aWXGkz257bLvKJLq3vhWW21HJjoOm2e0GYqmvbwjkt8/edit#gid=0

**Comment by gabsie** [comment]
3. Jeena I am OK to call that column 'Status'. Under it I as the primary user from below, I would expect either Download/Explore, or if not, text Expected 2024



Basically, there are two users, for which the needs are different.
User of the **data portal/consumer**:
is this dataset available for me to Explore/Download or not?
if yes - ‘Explore/Download’ button (depends what we are giving them whe somethig is released)
if no - text ‘Available 2024’
2. User of the spreadsheet - more **internal stakeholder/collaborator**
how are the DPCs getting on with data availability, ad what is their status?
Expected 2024
Uploaded etc
As we at the moment are looking at the first user for the data catalogue, I feel we should just address the first user's needs in the design. Will copy this in the requiremets for the designner as well
