### ISSUE TITLE
Get content for FAQ's

### ISSUE THREAD

**Issue by sandsebi** [ebi-ait/data-catalogue#68]

**Comment by gabsie** [comment]
Hey, @sandsebi - FAQ's here. If they are too long, let me know
https://drive.google.com/drive/u/0/folders/1QPWL9jh3Fx4uGsaKugtICWTdhOFDXFqD

**Comment by sandsebi** [comment]
@gabsie Please see the 'Preview' with the new content above

**Comment by sandsebi** [comment]
@gabsie do you want the hyperlink to the [Full list of genes to be studied under MorPhic.](https://morphic-genelist-app.shinyapps.io/shiny_genesetexplore/) to work within the FAQ as well?

**Comment by gabsie** [comment]
yes, if that's possible, Sandeep!
