### ISSUE TITLE
home grown value set filter

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/data-catalogue#7]
- [x] easy adding/removing filtered fields
- [x] split comma separated values so user can select individual values
- [ ] value sorting

**Comment by theisuru** [comment]
Test filter is implmented using angular multi select and ag-grid external filters. This can be seen [here](https://lxdg2y-4200.csb.app/). 
Once we agree this is the way forward, will implement it as a generic filter list which can be added as an configuration.
