### ISSUE TITLE
Managing Metadata in Catalogue

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/data-catalogue#82]
Based on the Catalogue concept document, there are several requirements needed for the eLwazi catalogue. This ticket looks at the requirement for allowing managing metadata changes. This can take any form, such as json file updates or a more complex real-time method of manging metadata. 

> Manage Metadata: Catalogue and Metadata Managers (see User Roles below) should be able to manage metadata pertaining to projects listed in the Catalogue. This includes:
> Adding new datasets (specifically, metadata of datasets).
> Editing existing dataset metadata fields.
> Editing existing project metadata fields.
> Removing dataset records (Catalogue Managers only).

**Comment by snathanvj** [comment]
@amnonkhen  do you have any proposal for the technology choice here. I am thinking of python+fastAPI+mongodb.

**Comment by Jeena-Rajan** [comment]
Closing this ticket as has been somewhat replaced with [#34](https://app.zenhub.com/workspaces/fairification-63c67b0688ee4e002b2890b3/issues/gh/ebi-ait/data-catalogue/34)
