### ISSUE TITLE
filter control out of sync visually with selection

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/data-catalogue#83]
There are a few problems with the filter controls:

- after selecting an option it remains in the list of options to choose
- after clicking the X to deselect an option, the option list remains open
- the checkboxes are not necessary
In the example in the angular material website the once an option in is selected it appears as a chip and removed from the list of available options.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3dpQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8824cae9d855b9fff747fa43c05e3dae947b37ad/Screen%20Recording%202024-02-02%20at%2011.27.34%E2%80%AFam.mov)

**Comment by theisuru** [comment]
I was mostly following the figma design, so the 1 and 3 are according to the design. 
For 2, I will check how to close option list once deselect is pressed. 

Let me know if we are going away from the figma design and these changes should be made.
