### ISSUE TITLE
grid customisation - hidden columns

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/data-catalogue#87]
Acceptance Criteria:
- [x] grid customisation instructions are recorded in a single json file
- [x] one customisation supported: hiding columns

example configuration file - `config.ts`:
`hide` attribute is optional, defaults to false.
```json
export const GRID_CONFIG: ColumnConfiguration[] = [
        {
            name: "title",
        },
        {
            name: "dsIAfricaAffiliation",
        },
        {
            name: "description",
            hide: true
        },
        {
            name: "keywords",
        }
    ]
;
```

**Comment by snathanvj** [comment]
@amnonkhen 
> grid customisation instructions are recorded in a single json file

it means, we already have schema.json, we could add hide:true/false in the schema.json or do we need another json file for customisation.

**Comment by snathanvj** [comment]
https://github.com/ebi-ait/data-catalogue-frontend/pull/2
