### ISSUE TITLE
configurable side filters

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/data-catalogue#95]
acceptance criteria
- [x] side filters appear in a sidebar
- [ ] nice to have - sidebar is collapsible
- [ ] a side filter drop down, presents as options the values of a field allows single selection 
- [ ] nice to have - sorted values in the option list
- [ ] nice to have - multiple selection in the option list
- [x] in the "visualisation configuration file" choose which columns appear on the side filters
- [ ] no styling configuration is necessary

**Comment by snathanvj** [comment]
https://github.com/ebi-ait/data-catalogue-frontend/pull/9
